// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(HeadwayRs)
import HeadwayRs
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_headway_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_headway_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureHeadwayInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol BoundsProtocol: AnyObject, Sendable {
    
}
open class Bounds: BoundsProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_headway_fn_clone_bounds(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_headway_fn_free_bounds(handle, $0) }
    }

    
public static func nesw(maxLat: Double, maxLon: Double, minLat: Double, minLon: Double) -> Bounds  {
    return try!  FfiConverterTypeBounds_lift(try! rustCall() {
    uniffi_headway_fn_constructor_bounds_nesw(
        FfiConverterDouble.lower(maxLat),
        FfiConverterDouble.lower(maxLon),
        FfiConverterDouble.lower(minLat),
        FfiConverterDouble.lower(minLon),$0
    )
})
}
    

    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBounds: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Bounds

    public static func lift(_ handle: UInt64) throws -> Bounds {
        return Bounds(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Bounds) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bounds {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Bounds, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBounds_lift(_ handle: UInt64) throws -> Bounds {
    return try FfiConverterTypeBounds.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBounds_lower(_ value: Bounds) -> UInt64 {
    return FfiConverterTypeBounds.lower(value)
}






public protocol ExtractProgress: AnyObject, Sendable {
    
    func onProgress(progress: Double) 
    
}
open class ExtractProgressImpl: ExtractProgress, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_headway_fn_clone_extractprogress(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_headway_fn_free_extractprogress(handle, $0) }
    }

    

    
open func onProgress(progress: Double)  {try! rustCall() {
    uniffi_headway_fn_method_extractprogress_on_progress(
            self.uniffiCloneHandle(),
        FfiConverterDouble.lower(progress),$0
    )
}
}
    

    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceExtractProgress {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceExtractProgress = UniffiVTableCallbackInterfaceExtractProgress(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterTypeExtractProgress.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface ExtractProgress: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterTypeExtractProgress.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface ExtractProgress: handle missing in uniffiClone")
            }
        },
        onProgress: { (
            uniffiHandle: UInt64,
            progress: Double,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeExtractProgress.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onProgress(
                     progress: try FfiConverterDouble.lift(progress)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceExtractProgress> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceExtractProgress>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitExtractProgress() {
    uniffi_headway_fn_init_callback_vtable_extractprogress(UniffiCallbackInterfaceExtractProgress.vtablePtr)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeExtractProgress: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<ExtractProgress>()

    typealias FfiType = UInt64
    typealias SwiftType = ExtractProgress

    public static func lift(_ handle: UInt64) throws -> ExtractProgress {
        if ((handle & 1) == 0) {
            // Rust-generated handle, construct a new class that uses the handle to implement the
            // interface
            return ExtractProgressImpl(unsafeFromHandle: handle)
        } else {
            // Swift-generated handle, get the object from the handle map
            return try handleMap.remove(handle: handle)
        }
    }

    public static func lower(_ value: ExtractProgress) -> UInt64 {
         if let rustImpl = value as? ExtractProgressImpl {
             // Rust-implemented object.  Clone the handle and return it
            return rustImpl.uniffiCloneHandle()
         } else {
            // Swift object, generate a new vtable handle and return that.
            return handleMap.insert(obj: value)
         }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ExtractProgress {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: ExtractProgress, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeExtractProgress_lift(_ handle: UInt64) throws -> ExtractProgress {
    return try FfiConverterTypeExtractProgress.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeExtractProgress_lower(_ value: ExtractProgress) -> UInt64 {
    return FfiConverterTypeExtractProgress.lower(value)
}






/**
 * A thin wrapper around PMTiles ExtractPlan so we can export it
 */
public protocol ExtractionPlanProtocol: AnyObject, Sendable {
    
    func tileDataLength()  -> UInt64
    
}
/**
 * A thin wrapper around PMTiles ExtractPlan so we can export it
 */
open class ExtractionPlan: ExtractionPlanProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_headway_fn_clone_extractionplan(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_headway_fn_free_extractionplan(handle, $0) }
    }

    

    
open func tileDataLength() -> UInt64  {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_headway_fn_method_extractionplan_tile_data_length(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeExtractionPlan: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = ExtractionPlan

    public static func lift(_ handle: UInt64) throws -> ExtractionPlan {
        return ExtractionPlan(unsafeFromHandle: handle)
    }

    public static func lower(_ value: ExtractionPlan) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ExtractionPlan {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: ExtractionPlan, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeExtractionPlan_lift(_ handle: UInt64) throws -> ExtractionPlan {
    return try FfiConverterTypeExtractionPlan.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeExtractionPlan_lower(_ value: ExtractionPlan) -> UInt64 {
    return FfiConverterTypeExtractionPlan.lower(value)
}






public protocol HeadwayServerProtocol: AnyObject, Sendable {
    
    /**
     * Downloads a complete pmtiles file from a URL to the system tileset directory.
     *
     * System tilesets are permanent and cannot be deleted by users (unlike user-extracted regions).
     * Typically used for bundling low-resolution global overview tiles.
     * Skips download if the destination file already exists.
     *
     * Returns `true` if the file was downloaded, `false` if it already existed.
     */
    func downloadSystemPmtilesIfNecessary(sourceUrl: String, destinationFilename: String) async throws  -> Bool
    
    /**
     * Downloads the tile data for an extracted region based on the prepared plan.
     *
     * Call [`Self::prepare_pmtiles_extract`] first to get an [`ExtractionPlan`].
     *
     * Upon completion, the extracted tileset will automatically be served by the tileserver, though
     * you may need to clear your map client's tile cache if it had previously requested the
     * area covered by the newly added extract.
     */
    func extractPmtilesRegion(plan: ExtractionPlan, progressCallback: ExtractProgress?) async throws  -> RegionRecord
    
    /**
     * Plans a pmtiles extraction without downloading the tile data. It does require traversing
     * the remote index directories.
     *
     * Use this to determine how much data would be downloaded before committing to the extraction.
     * Call [`Self::extract_pmtiles_region`] with the returned plan to perform the actual download.
     */
    func preparePmtilesExtract(bounds: Bounds, progressCallback: ExtractProgress?) async throws  -> ExtractionPlan
    
    /**
     * Delete a previously downloaded pmtiles region extract
     */
    func removePmtilesExtract(fileName: String) async throws 
    
    /**
     * Starts the server on the given address
     */
    func start(bindAddr: String) async throws 
    
}
open class HeadwayServer: HeadwayServerProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_headway_fn_clone_headwayserver(self.handle, $0) }
    }
    /**
     * `storage_dir`: Persists server data like pmtiles extracts
     * `extract_source_url`: Should point to a planet file suitable for running pmtile extracts against
     */
public convenience init(storageDir: String, extractSourceUrl: String)async throws  {
    let handle =
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_headway_fn_constructor_headwayserver_new(FfiConverterString.lower(storageDir),FfiConverterString.lower(extractSourceUrl)
                )
            },
            pollFunc: ffi_headway_rust_future_poll_u64,
            completeFunc: ffi_headway_rust_future_complete_u64,
            freeFunc: ffi_headway_rust_future_free_u64,
            liftFunc: FfiConverterTypeHeadwayServer_lift,
            errorHandler: FfiConverterTypeError_lift
        )
        
        .uniffiCloneHandle()
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_headway_fn_free_headwayserver(handle, $0) }
    }

    

    
    /**
     * Downloads a complete pmtiles file from a URL to the system tileset directory.
     *
     * System tilesets are permanent and cannot be deleted by users (unlike user-extracted regions).
     * Typically used for bundling low-resolution global overview tiles.
     * Skips download if the destination file already exists.
     *
     * Returns `true` if the file was downloaded, `false` if it already existed.
     */
open func downloadSystemPmtilesIfNecessary(sourceUrl: String, destinationFilename: String)async throws  -> Bool  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_headway_fn_method_headwayserver_download_system_pmtiles_if_necessary(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(sourceUrl),FfiConverterString.lower(destinationFilename)
                )
            },
            pollFunc: ffi_headway_rust_future_poll_i8,
            completeFunc: ffi_headway_rust_future_complete_i8,
            freeFunc: ffi_headway_rust_future_free_i8,
            liftFunc: FfiConverterBool.lift,
            errorHandler: FfiConverterTypeError_lift
        )
}
    
    /**
     * Downloads the tile data for an extracted region based on the prepared plan.
     *
     * Call [`Self::prepare_pmtiles_extract`] first to get an [`ExtractionPlan`].
     *
     * Upon completion, the extracted tileset will automatically be served by the tileserver, though
     * you may need to clear your map client's tile cache if it had previously requested the
     * area covered by the newly added extract.
     */
open func extractPmtilesRegion(plan: ExtractionPlan, progressCallback: ExtractProgress?)async throws  -> RegionRecord  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_headway_fn_method_headwayserver_extract_pmtiles_region(
                    self.uniffiCloneHandle(),
                    FfiConverterTypeExtractionPlan_lower(plan),FfiConverterOptionTypeExtractProgress.lower(progressCallback)
                )
            },
            pollFunc: ffi_headway_rust_future_poll_u64,
            completeFunc: ffi_headway_rust_future_complete_u64,
            freeFunc: ffi_headway_rust_future_free_u64,
            liftFunc: FfiConverterTypeRegionRecord_lift,
            errorHandler: FfiConverterTypeError_lift
        )
}
    
    /**
     * Plans a pmtiles extraction without downloading the tile data. It does require traversing
     * the remote index directories.
     *
     * Use this to determine how much data would be downloaded before committing to the extraction.
     * Call [`Self::extract_pmtiles_region`] with the returned plan to perform the actual download.
     */
open func preparePmtilesExtract(bounds: Bounds, progressCallback: ExtractProgress?)async throws  -> ExtractionPlan  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_headway_fn_method_headwayserver_prepare_pmtiles_extract(
                    self.uniffiCloneHandle(),
                    FfiConverterTypeBounds_lower(bounds),FfiConverterOptionTypeExtractProgress.lower(progressCallback)
                )
            },
            pollFunc: ffi_headway_rust_future_poll_u64,
            completeFunc: ffi_headway_rust_future_complete_u64,
            freeFunc: ffi_headway_rust_future_free_u64,
            liftFunc: FfiConverterTypeExtractionPlan_lift,
            errorHandler: FfiConverterTypeError_lift
        )
}
    
    /**
     * Delete a previously downloaded pmtiles region extract
     */
open func removePmtilesExtract(fileName: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_headway_fn_method_headwayserver_remove_pmtiles_extract(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(fileName)
                )
            },
            pollFunc: ffi_headway_rust_future_poll_void,
            completeFunc: ffi_headway_rust_future_complete_void,
            freeFunc: ffi_headway_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
    /**
     * Starts the server on the given address
     */
open func start(bindAddr: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_headway_fn_method_headwayserver_start(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(bindAddr)
                )
            },
            pollFunc: ffi_headway_rust_future_poll_void,
            completeFunc: ffi_headway_rust_future_complete_void,
            freeFunc: ffi_headway_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHeadwayServer: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = HeadwayServer

    public static func lift(_ handle: UInt64) throws -> HeadwayServer {
        return HeadwayServer(unsafeFromHandle: handle)
    }

    public static func lower(_ value: HeadwayServer) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HeadwayServer {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: HeadwayServer, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeadwayServer_lift(_ handle: UInt64) throws -> HeadwayServer {
    return try FfiConverterTypeHeadwayServer.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeadwayServer_lower(_ value: HeadwayServer) -> UInt64 {
    return FfiConverterTypeHeadwayServer.lower(value)
}






public protocol RegionRecordProtocol: AnyObject, Sendable {
    
    func bounds()  -> Bounds
    
    func fileName()  -> String
    
    func fileSize()  -> UInt64
    
}
open class RegionRecord: RegionRecordProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_headway_fn_clone_regionrecord(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_headway_fn_free_regionrecord(handle, $0) }
    }

    

    
open func bounds() -> Bounds  {
    return try!  FfiConverterTypeBounds_lift(try! rustCall() {
    uniffi_headway_fn_method_regionrecord_bounds(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func fileName() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_headway_fn_method_regionrecord_file_name(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func fileSize() -> UInt64  {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_headway_fn_method_regionrecord_file_size(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRegionRecord: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = RegionRecord

    public static func lift(_ handle: UInt64) throws -> RegionRecord {
        return RegionRecord(unsafeFromHandle: handle)
    }

    public static func lower(_ value: RegionRecord) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RegionRecord {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: RegionRecord, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRegionRecord_lift(_ handle: UInt64) throws -> RegionRecord {
    return try FfiConverterTypeRegionRecord.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRegionRecord_lower(_ value: RegionRecord) -> UInt64 {
    return FfiConverterTypeRegionRecord.lower(value)
}




public enum Error: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Runtime(message: String)
    
    case InvalidInput(message: String)
    
    case Serve(message: String)
    
    case PmTiles(message: String)
    
    case Reqwest(message: String)
    
    case Io(message: String)
    
    case WithContext(message: String)
    

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension Error: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeError: FfiConverterRustBuffer {
    typealias SwiftType = Error

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Error {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Runtime(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .InvalidInput(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .Serve(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .PmTiles(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .Reqwest(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .Io(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .WithContext(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Error, into buf: inout [UInt8]) {
        switch value {

        

        
        case .Runtime(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .InvalidInput(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .Serve(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .PmTiles(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .Reqwest(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .Io(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))
        case .WithContext(_ /* message is ignored*/):
            writeInt(&buf, Int32(7))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeError_lift(_ buf: RustBuffer) throws -> Error {
    return try FfiConverterTypeError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeError_lower(_ value: Error) -> RustBuffer {
    return FfiConverterTypeError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum LogLevel: Equatable, Hashable {
    
    /**
     * A level lower than all log levels.
     */
    case off
    /**
     * Corresponds to the `Error` log level.
     */
    case error
    /**
     * Corresponds to the `Warn` log level.
     */
    case warn
    /**
     * Corresponds to the `Info` log level.
     */
    case info
    /**
     * Corresponds to the `Debug` log level.
     */
    case debug
    /**
     * Corresponds to the `Trace` log level.
     */
    case trace





}

#if compiler(>=6)
extension LogLevel: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLogLevel: FfiConverterRustBuffer {
    typealias SwiftType = LogLevel

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LogLevel {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .off
        
        case 2: return .error
        
        case 3: return .warn
        
        case 4: return .info
        
        case 5: return .debug
        
        case 6: return .trace
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: LogLevel, into buf: inout [UInt8]) {
        switch value {
        
        
        case .off:
            writeInt(&buf, Int32(1))
        
        
        case .error:
            writeInt(&buf, Int32(2))
        
        
        case .warn:
            writeInt(&buf, Int32(3))
        
        
        case .info:
            writeInt(&buf, Int32(4))
        
        
        case .debug:
            writeInt(&buf, Int32(5))
        
        
        case .trace:
            writeInt(&buf, Int32(6))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLogLevel_lift(_ buf: RustBuffer) throws -> LogLevel {
    return try FfiConverterTypeLogLevel.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLogLevel_lower(_ value: LogLevel) -> RustBuffer {
    return FfiConverterTypeLogLevel.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeExtractProgress: FfiConverterRustBuffer {
    typealias SwiftType = ExtractProgress?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeExtractProgress.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeExtractProgress.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureHeadwayInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
/**
 * Initializes the logger for the headway library.
 * This should be called once at application startup.
 * On iOS, this will use OSLog with the specified subsystem and category.
 */
public func enableLogging(subsystem: String, logLevel: LogLevel)  {try! rustCall() {
    uniffi_headway_fn_func_enable_logging(
        FfiConverterString.lower(subsystem),
        FfiConverterTypeLogLevel_lower(logLevel),$0
    )
}
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_headway_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_headway_checksum_func_enable_logging() != 41416) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_headway_checksum_method_regionrecord_bounds() != 3290) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_headway_checksum_method_regionrecord_file_name() != 30106) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_headway_checksum_method_regionrecord_file_size() != 2008) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_headway_checksum_method_extractprogress_on_progress() != 31780) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_headway_checksum_method_extractionplan_tile_data_length() != 57729) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_headway_checksum_method_headwayserver_download_system_pmtiles_if_necessary() != 52934) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_headway_checksum_method_headwayserver_extract_pmtiles_region() != 64704) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_headway_checksum_method_headwayserver_prepare_pmtiles_extract() != 50759) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_headway_checksum_method_headwayserver_remove_pmtiles_extract() != 2063) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_headway_checksum_method_headwayserver_start() != 33350) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_headway_checksum_constructor_bounds_nesw() != 31160) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_headway_checksum_constructor_headwayserver_new() != 53663) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitExtractProgress()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureHeadwayInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all